### ISSUE TITLE
Change web server in the architecture diagram to Tomcat

### ISSUE THREAD

**Issue by danielchabr** [Damell/Korean-dining-advisor#18]

**Comment by wook-jae** [comment]
![model1](https://cloud.githubusercontent.com/assets/14276869/10559193/c6dcfad0-7525-11e5-8014-9c281b8c18e6.png)

In developing server, we will use Tomcat open source. There are databases and application in server. And in server, they can give and receive relevant data. Application receive necessary information from each API. And user can access to application through cellphone
