### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by torbentee** [Damell/Korean-dining-advisor#19]
What do you think about one of these as a logo?
![korean_dining_advisor01](https://cloud.githubusercontent.com/assets/4125656/10661411/ccc3570c-78e8-11e5-9ab1-15ca27d8ea65.png)
![korean_dining_advisor02](https://cloud.githubusercontent.com/assets/4125656/10661413/cedc7ef6-78e8-11e5-9ead-e53eadb797cd.png)

**Comment by danielchabr** [comment]
WOOOW. Both look great, but I simply love the all the information contained in the first one while still looking nice. Big THUMBS UP :)

**Comment by danielchabr** [comment]
JaeWook? Your preferences? Torben, will you please include it in the presentation when you edit it? :)
