### ISSUE TITLE
Use HTTPS

### ISSUE THREAD

**Issue by torbentee** [Damell/Korean-dining-advisor#29]
It would be nice to use a encrypted connection especially for the authentication. 
In the week around November 15th there will start a service on [letsencrypt.org](https://letsencrypt.org/). It is free maybe we can have a look on it.

**Comment by danielchabr** [comment]
Looks very interesting. Thank you for noting it, I might use it for my Bibliofair app. For our project though we do not need to use it. There is https provided already. Just go to https://kda-damell.rhcloud.com/ and you will access the same service via https. In the app settings we can probably disable connections coming through http

**Comment by torbentee** [comment]
oh how nice :+1:. You're welcome!
