### ISSUE TITLE
Architecture diagram

### ISSUE THREAD

**Issue by danielchabr** [Damell/Korean-dining-advisor#4]
a high level architecture diagram (main components and their connections) + explanation

**Comment by wook-jae** [comment]
![14](https://cloud.githubusercontent.com/assets/14276869/10545169/494f0388-7462-11e5-8b93-4e0c539ff35d.PNG)

In developing server, we will use docker and glassfish open source. There are databases and application in server. And in server, they can give and receive relevant data. Application receive necessary information from each API. And user can access to application through cell phone
